# docker-compose-hadoop.yml
version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - "9870:9870"   
      - "8020:8020"   
    environment:
      - CLUSTER_NAME=saham-meter
    env_file:
      - ./hadoop.env
    volumes:
      - hadoop_namenode:/hadoop/dfs/name

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    ports:
      - "9864:9864"
      - "9866:9866"
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
      HDFS_CONF_dfs_datanode_address: "0.0.0.0:9866"
      HDFS_CONF_dfs_datanode_http_address: "0.0.0.0:9864"
      HDFS_CONF_dfs_datanode_hostname: "100.74.49.87"
      HDFS_CONF_dfs_client_use_datanode_hostname: "true"
    env_file:
      - ./hadoop.env
    volumes:
      - hadoop_datanode:/hadoop/dfs/data

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    restart: always
    ports:
      - "8088:8088"
    environment:
      SERVICE_PRECONDITION: "namenode:9870 namenode:8020 datanode:9864"
    env_file:
      - ./hadoop.env

  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9870 namenode:8020 datanode:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env

volumes:
  hadoop_namenode:
  hadoop_datanode: